### ISSUE TITLE
Investigate auto generating docs by adding more information to the yaml

### ISSUE THREAD

**Issue by tas50** [chef/cookstyle#277]
## Specification

See if it makes sense to add additional fields to the yaml config. We could potentially add a docs_description field that included markdown describing how to use the cop. Ideally we end up with content that is at a minimum as good as what we had on foodcritic.io.

The current data available for each rule is similar to this:

```yml
Chef/LocaleDeprecatedLcAllProperty:
  Description: The local resource's lc_all property has been deprecated and will be
    removed in Chef Infra Client 16
  Enabled: true
  VersionAdded: 5.5.0
  Exclude:
  - "/Users/tsmith/dev/work/cookstyle/**/metadata.rb"
```

We could certainly generate docs with that information, and it would be better than nothing, but I think we can do a lot better.

## Downstream Impact

The docs team will most likely consume this information to populate the docs site. Obviously this is going to require a lot of coordination so we can figure out how to best meet both of our needs.
